name: Publish Quarto Blog

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to checkout the repository
      pages: write # Needed to deploy to GitHub Pages
      id-token: write # Needed for GitHub Pages authentication

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # Cache pip packages for faster builds

      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render Quarto site
        uses: quarto-dev/quarto-actions/render@v2

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
